spring:
  profiles:
    active: peer1
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/
server:
  port: 8761

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/
server:
  port: 8762
